// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Character struct {
	ID          int      `json:"id"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Comics      []*Comic `json:"comics"`
	Stories     []*Story `json:"stories"`
}

type Comic struct {
	ID          int          `json:"id"`
	Title       string       `json:"title"`
	Description string       `json:"description"`
	Stories     []*Story     `json:"stories"`
	Characters  []*Character `json:"characters"`
}

type Story struct {
	ID          int          `json:"id"`
	Title       string       `json:"title"`
	Description string       `json:"description"`
	Comics      []*Comic     `json:"comics"`
	Characters  []*Character `json:"characters"`
}
